#define DIALOGID_NSIME_SETTING_JP   100
#define DIALOGID_NSIME_SETTING_EN   200

#define DID_NSIME_CHKB_MSLIKE_ENABLE 101
#define DID_NSIME_GROUP_MSLIKE_SET  102
#define DID_NSIME_CHKB_MSLIKE_DELAY 103
#define DID_NSIME_GROUP_MSLIKE_ACT  104
#define DID_NSIME_LTXT_NLS          105
#define DID_NSIME_LTXT_WIDTH        106
#define DID_NSIME_LTXT_ROMAJI       107
#define DID_NSIME_LTXT_MSLIKE_ACTIVE 110
#define DID_NSIME_COMB_MSLIKE_ACT_NLS 111
#define DID_NSIME_COMB_MSLIKE_ACT_WIDTH 112
#define DID_NSIME_COMB_MSLIKE_ACT_ROMAJI 113
#define DID_NSIME_LTXT_MSLIKE_DEACTIVE 116
#define DID_NSIME_COMB_MSLIKE_DEA_NLS 117
#define DID_NSIME_COMB_MSLIKE_DEA_WIDTH 118
#define DID_NSIME_COMB_MSLIKE_DEA_ROMAJI 119
#define DID_NSIME_LTXT_VISIBLE_ENABLE 123
#define DID_NSIME_RADIO_VISIBLE_ALWAYS 124
#define DID_NSIME_RADIO_VISIBLE_CANUSE 125
#define DID_NSIME_RADIO_VISIBLE_ONLYUSE 126

