#define NSIME_DEFAULT_RES 100

#define NSIME_MENUID_INSERT_JP 100
#define NSIME_MENUID_INSERT_EN 200
#define NSIME_CMDID_SETTINGS 101

#define NSIME_STRID_CLIENT_CAPTION_JP 101
#define NSIME_STRID_ERROR_NOIME_JP 102
#define NSIME_STRID_ERROR_NODLL_JP 103
#define NSIME_STRID_ERROR_INVALVER_JP 104

#define NSIME_STRID_NLS_ALPHANUM_JP 111
#define NSIME_STRID_NLS_HIRAGANA_JP 112
#define NSIME_STRID_NLS_KATAKANA_JP 113
#define NSIME_STRID_WIDTH_HALF_JP 114
#define NSIME_STRID_WIDTH_FULL_JP 115
#define NSIME_STRID_ROMAJI_OFF_JP 116
#define NSIME_STRID_ROMAJI_ON_JP 117

#define NSIME_STRID_CLIENT_CAPTION_EN 201
#define NSIME_STRID_ERROR_NOIME_EN 202
#define NSIME_STRID_ERROR_NODLL_EN 203
#define NSIME_STRID_ERROR_INVALVER_EN 204

#define NSIME_STRID_NLS_ALPHANUM_EN 211
#define NSIME_STRID_NLS_HIRAGANA_EN 212
#define NSIME_STRID_NLS_KATAKANA_EN 213
#define NSIME_STRID_WIDTH_HALF_EN 214
#define NSIME_STRID_WIDTH_FULL_EN 215
#define NSIME_STRID_ROMAJI_OFF_EN 216
#define NSIME_STRID_ROMAJI_ON_EN 217

#define NSIME_STRID_NLS_HANGEUL_EN 218
#define NSIME_STRID_NLS_PRC_EN 219
#define NSIME_STRID_NLS_TAIWAN_EN 220
#define NSIME_STRID_NLS_ANYTHING_EN 221

